# Additional topics of interest

The literature on mediation analysis has grown considerably in the last few
decades and there are now many novel methods to tackle important questions with
complex data structures. While we are unable to cover all these interesting
methods in this workshop, here we provide a few references for further reading.

This list is not meant to be comprehensive, just some of our own work and some
work by others that we know and consider interesting.

## Mediation with time-varying treatments, mediators, and covariates

The issue of intermediate confounding is exacerbated in a setting with multiple
treatments and mediators measured at various time points. Here are a couple of
papers on this topic that are interesting:

- [Mediation analysis with time varying exposures and
  mediators](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssb.12194)
  by Tyler J. VanderWeele and Eric J. Tchetgen Tchetgen
- [Longitudinal Mediation Analysis with Time-varying Mediators and
  Exposures, with Application to Survival
  Outcomes](https://www.degruyter.com/document/doi/10.1515/jci-2016-0006/html)
  by  Wenjing Zheng and Mark J. van der Laan
- [Efficient and flexible causal mediation with time-varying
  mediators, treatments, and
  confounders](https://arxiv.org/abs/2203.15085) by Iván Díaz,
  Nicholas Williams, and Kara E. Rudolph

## Mediation with monotonicity of A-Z relationship

- [On identification of natural direct effects when a confounder of the mediator
  is directly affected by
  exposure](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4230499/) by Eric J.
  Tchetgen Tchetgen and Tyler J. VanderWeele
- [Efficient and flexible estimation of natural mediation effects under
  intermediate confounding and monotonicity
  constraints](http://arxiv.org/abs/2205.04408) by Kara E. Rudolph and Iván
  Díaz

## Mediation with instrumental variables

- [Direct and indirect treatment effects–causal chains and mediation analysis
  with instrumental
  variables](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssb.12232)
  by Markus Frolich and Martin Huber
- [Causal mediation with instrumental
  variables](https://arxiv.org/abs/2112.13898) by Kara E. Rudolph, Nicholas
  Williams, and Iván Díaz

## Mediation with separable effects

* [An Interventionist Approach to Mediation
  Analysis](https://dl.acm.org/doi/abs/10.1145/3501714.3501754) by James M.
  Robins, Thomas S. Richardson, and Ilya Shpitser
* [Conditional Separable
  Effects](https://www.tandfonline.com/doi/abs/10.1080/01621459.2022.2071276)
  by Mats J. Stensrud, James M. Robins, Aaron Sarvet, Eric J. Tchetgen
  Tchetgen, and Jessica G. Young
* [Separable Effects for Causal Inference in the Presence of Competing
  Events](https://www.tandfonline.com/doi/abs/10.1080/01621459.2020.1765783) by
  Mats J. Stensrud, Jessica G. Young, Vanessa Didelez, James M. Robins, and
  Miguel A. Hernán
* [A Generalized Theory of Separable Effects in Competing Event
  Settings](https://link.springer.com/article/10.1007/s10985-021-09530-8) by
  Mats J. Stensrud, Miguel A. Hernán, Eric J. Tchetgen Tchetgen, James M.
  Robins, Vanessa Didelez, and Jessica G. Young
